# OpenAI API test

In [1]:
# import openai
# from dotenv import load_dotenv
# import os

In [2]:
# load_dotenv()  # Load the environment variables from the .env file
# openai.api_key = os.getenv('OPENAI_API_KEY')

# models = openai.Model.list()

# for model in models['data']:
#     print(model['id'])

dall-e-3
text-embedding-3-large
text-embedding-3-small
gpt-4-0125-preview
text-embedding-ada-002
dall-e-2
tts-1
gpt-4o-2024-08-06
tts-1-hd-1106
tts-1-1106
tts-1-hd
babbage-002
gpt-4-turbo-preview
gpt-3.5-turbo
gpt-3.5-turbo-1106
whisper-1
gpt-3.5-turbo-16k
gpt-4o
gpt-4o-mini-2024-07-18
gpt-3.5-turbo-instruct-0914
gpt-4o-2024-05-13
gpt-4o-mini
gpt-3.5-turbo-0125
gpt-4-0613
gpt-3.5-turbo-instruct
gpt-4-1106-preview
gpt-4
chatgpt-4o-latest
gpt-4-turbo-2024-04-09
davinci-002
gpt-4-turbo

In [3]:
# openai.api_key = os.getenv('OPENAI_API_KEY')


# model = "gpt-4o-mini"
# temperature = 0.3
# max_tokens = 500

# def get_summary(text):
#     system_message = """
#     You are a professional summarizer of philosophy texts.
#     Your summaries are efficient because they summarize the text in a way
#     that is easy for data scientists
#     to vectorize and embed the texts for NLP.
#     """
#     prompt = f"""
#     Summarize the philosophy text in a way that gives only
#     essential information to vectorize and embed the text. The summary should be
#     only 2 sentences long! It should be really short and just have the keywords of
#     important ideas of the passage! Here is the text:{text}
#     """

#     messages = [
#         {'role': 'system', 'content': system_message},
#         {'role': 'user', 'content': prompt}
#     ]


#     completion = openai.ChatCompletion.create(
#         model=model,
#         messages=messages,
#         temperature=temperature,
#         max_tokens=max_tokens
#     )
#     return completion.choices[0].message['content']

In [5]:
# data['gpt40_summary'] = data.text.apply(get_summary)

In [6]:
# data.to_csv('df_gpt_summaries.csv',sep=',', index=True)

# Recommender system

In [1]:
import pandas as pd
data = pd.read_csv('/home/jeanluca/code/JeanLucaSchindler/FUSE/raw_data/df_gpt_summaries.csv')
data = data.set_index(data['index'])

In [5]:
data = data.drop(['Unnamed: 0', 'index'], axis=1)

In [6]:
import string
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

def preprocessing(sentence):

    # Remove whitespace
    sentence = sentence.strip()

    # Lowercase characters
    sentence = sentence.lower()

    #stop_word
    stop_words = set(stopwords.words('english'))
    sentence = ' '.join(word for word in sentence.split() if word not in stop_words)

    # Remove numbers
    sentence = ''.join(char for char in sentence if not char.isdigit())

    # Remove punctuation
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '')

    # Tokenize
    sentence = word_tokenize(sentence)

    # Lemmatize
    verbs_lemmed = [
        WordNetLemmatizer().lemmatize(word, pos='v')
        for word in sentence
    ]
    nouns_lemmed = [
        WordNetLemmatizer().lemmatize(word, pos='n')
        for word in verbs_lemmed
    ]
    return ' '.join(word for word in nouns_lemmed)

In [7]:
data['clean_text'] = data.gpt40_summary.apply(preprocessing)

In [8]:
data

,text,gpt40_summary,clean_text
index,,,
E1.5.A.1.1_REF1_PSI,"""THE FOCUSSING ILLUSION. Any aspect of life to...",Focusing illusion: attention distorts life eva...,focus illusion attention distort life evaluati...
E1.5.A.1.1_REF2_PSI,"""MISWANTING"" ""Daniel Gilbert and Timothy Wilso...",Miswanting; affective forecasting errors; focu...,miswanting affective forecast error focus illu...
E1.5.A.1.1_REF2.1_PH,Non-philosophers are unable to choose the good...,Plato's myth of Er suggests non-philosophers l...,plato myth er suggest nonphilosophers lack abi...
E1.5.A.1.1_REF2.1.a_PH,"""In Plato's myth of Er the Pamphylian, the bas...",Plato's myth of Er explores the relationship b...,plato myth er explore relationship happiness v...
E1.5.A.1.1_REF2.1.b_SONG,"Musical Illustration: Jacques Higelin, Tombé ...","Musical Illustration, Jacques Higelin, Tombé d...",musical illustration jacques higelin tombé du ...
...,...,...,...
E1.7.D.6.30_REF3_PH,"""""""Every moment beset by existence, immersed i...",Existence is often overlooked in modern though...,existence often overlook modern think lead dis...
E1.7.D.6.34_REF1_PO,"""""""A jar of basil gave me joy As if I were hav...","Keywords: joy, basil, lunch, Frank O'Hara, fra...",keywords joy basil lunch frank ohara fragrant ...
E1.7.D.6.34_REF2_PO,"""""""The broom is a witch's affair I angered the...","Keywords: broom, witch, cat, sheep, sugar, fea...",keywords broom witch cat sheep sugar feather m...
E1.7.D.6.34_REF3_PO,"""""""The kittiwake played a nasty trick on me Bu...","Kittiwake, horizon, gift, sky, live, laugh, cr...",kittiwake horizon gift sky live laugh cry forg...
E1.7.D.6.35_REF1_PH,"""""""Wisdom reveals to me, in understanding thin...",Wisdom emphasizes the equality of the world an...,wisdom emphasize equality world need selfalign...

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()

count_df = count_vectorizer.fit_transform(data['clean_text'])
count_df = pd.DataFrame(count_df.toarray())
count_df

,0,1,2,3,4,5,6,7,8,9,...,5895,5896,5897,5898,5899,5900,5901,5902,5903,5904
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1881,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1882,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1883,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
from sklearn.decomposition import TruncatedSVD

In [11]:
svd = TruncatedSVD(n_components=615)
trunc_df = svd.fit_transform(count_df)

In [12]:
print(svd.explained_variance_ratio_.sum())

0.8189672436643313

In [13]:
trunc_df = pd.DataFrame(trunc_df, columns=[f'component_{i+1}' for i in range(trunc_df.shape[1])])
latent_df = trunc_df.set_index(data.index)
latent_df

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,...,component_606,component_607,component_608,component_609,component_610,component_611,component_612,component_613,component_614,component_615
index,,,,,,,,,,,,,,,,,,,,,
E1.5.A.1.1_REF1_PSI,0.685782,-0.278326,0.730084,-0.403958,0.505860,0.335483,-0.147029,0.334495,0.068873,-0.101537,...,0.052117,-0.016349,0.059993,-0.152904,0.007025,-0.098441,0.009794,0.070217,0.077493,0.036341
E1.5.A.1.1_REF2_PSI,0.104925,-0.028110,-0.042473,-0.064859,0.081201,0.052470,-0.060299,0.006920,-0.035344,0.016500,...,0.044934,-0.018408,0.010997,-0.002075,0.148254,-0.086149,0.015539,-0.082238,-0.073771,0.068130
E1.5.A.1.1_REF2.1_PH,1.006658,-0.650826,1.488284,-0.519290,-0.276125,0.122545,-0.477996,-0.195153,0.286180,-0.070120,...,-0.033281,-0.108307,0.092816,0.003011,0.113465,-0.027339,-0.001650,-0.033741,0.040427,0.076910
E1.5.A.1.1_REF2.1.a_PH,1.352863,-0.297800,-0.504684,-1.244859,1.167358,-0.432455,-0.155953,-0.118495,-0.597548,-0.019923,...,-0.019569,-0.117373,0.016825,-0.029516,-0.019144,-0.178406,0.003306,0.056422,0.017242,0.103543
E1.5.A.1.1_REF2.1.b_SONG,0.147357,0.002398,-0.070247,0.048012,0.019983,0.061476,-0.158657,-0.003558,-0.059084,0.029850,...,0.018297,0.075110,-0.106461,0.013303,-0.044343,-0.063678,-0.031921,-0.048987,0.112044,0.058325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E1.7.D.6.30_REF3_PH,1.518076,-0.796555,-0.625955,-0.151076,-0.599084,-1.004915,1.561491,0.754102,-0.444203,0.307656,...,0.005533,-0.067506,-0.005185,0.008104,0.010225,0.055432,0.007394,0.034367,0.020592,0.080330
E1.7.D.6.34_REF1_PO,0.449135,0.446012,0.410987,0.017852,1.225522,0.274270,0.444179,0.380049,-0.459619,-0.238590,...,0.067596,-0.130041,0.154514,-0.341795,0.367861,0.148435,0.463841,-0.145595,0.356387,-0.248628
E1.7.D.6.34_REF2_PO,0.139837,0.299519,0.313169,0.340950,0.325531,0.076768,0.305929,-0.410721,-0.400900,0.242939,...,-0.002265,0.020770,0.013608,-0.004840,0.023789,0.002466,0.019213,0.005615,0.004058,0.005523
E1.7.D.6.34_REF3_PO,0.190756,-0.007648,0.088121,-0.022466,0.147578,0.029997,0.087724,-0.087716,-0.067908,0.091100,...,0.017271,-0.015065,0.039004,-0.071672,-0.134802,0.044193,-0.100101,0.012966,-0.069001,-0.100826
E1.7.D.6.35_REF1_PH,1.125456,-0.462683,-0.434015,-0.139280,-0.444064,-0.617994,0.677813,0.139219,-0.519527,-0.042359,...,0.011098,0.038644,-0.001219,0.011605,0.000142,0.088266,0.102994,-0.004280,0.011062,0.061209

In [14]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [43]:
# Compute cosine similarity for content matrix
content_similarities = cosine_similarity(np.array(latent_df.iloc[18]).reshape(1, -1), latent_df).flatten()

In [44]:
reco = pd.DataFrame(content_similarities)
reco = reco.set_index(data.index)
reco = reco.rename(columns={0:'similarity'})

In [45]:
top_reco = reco.sort_values(by=['similarity'], ascending=False).head(5)
top_reco

                        similarity
index
E1.5.A.3_REF3.1_SOC       1.000000
E1.5.A.3_REF1_SCI         0.510412
E1.5.A.3_REF3_SOC         0.460769
E1.5.B.1.6_REF1_LIT       0.435281
E1.5.B.13.1.b_REF2_LIT    0.406780

In [49]:
top_reco.index[0]

'E1.5.A.3_REF3.1_SOC'

In [46]:
data.loc[top_reco.index[0]]['text']

'"In the West, the received wisdom was that the young are the happiest and that happiness thereafter declines until middle age, followed by substantial recovery. But since 2006-10, as we shall see, happiness among the young (aged 15-24) has fallen sharply in North America – to a point where the young are less happy than the old. Youth happiness has also fallen (but less sharply) in Western Europe.  By contrast, happiness at every age has risen sharply in Central and Eastern Europe, so that young people are now equally happy in both parts of Europe. In the former Soviet Union and East Asia too there have been large increases in happiness at every age, while in South Asia and the Middle East and North Africa happiness has fallen at every age.  It is of course an issue to what extent these changes reflect generational changes that can be expected to persist as each generation gets older." (World Happiness Report 2024)  Read de full report: https://worldhappiness.report/'

In [47]:
data.loc[top_reco.index[1]]['text']

'"In her book on optimism bias and the life-cycle of happiness, neuroscientist Tali Sharot shares some data consistent with Eliot’s sentiment. This is the pattern of a typical person’s happiness over the course of a lifetime — a pattern that persists even when controlled for variables like marital status, health, and cultural climate:  Figure A: Average life satisfaction by age group  The data comes from behavioral economist Andrew Oswald’s research, which Sharot synthesizes:  \'Happiness and the ability to learn from bad news alter with age in reverse patterns. The latter follows an inverse U shape, while the former a more traditional U shape. The behavioral economist Andrew Oswald found that from about the time we are teenagers, our sense of happiness starts to decline, hitting rock bottom in our mid-40s (middle-age crisis, anyone?). Then our sense of happiness miraculously starts to go up again rapidly as we grow older. This finding contradicts the common assumption that people in their 60s, 70s, and 80s are less happy and satisfied than people in their 30s and 40s. […] All in all, Oswald tested a half million people in 72 countries, in both developing and developed nations. He observed the same pattern across all parts of the globe and across sexes. From Switzerland to Ecuador, from Romania to Singapore, Slovakia, Israel, Spain, Australia, and China. Happiness diminishes as we transition from childhood to adulthood and then starts rising as we grow wrinkles and acquire gray hair. And it’s not only we humans who slump in the middle and feel sunnier toward the end. Just recently, Oswald and colleagues demonstrated that even chimpanzees and orangutans appear to experience a similar pattern of midlife malaise.\'  The increase of happiness with age might have to do with the notion that attention, like a muscle, grows with training. Since happiness is so heavily anchored to our capacity for presence and so diminished by our mind-wandering, the ability to truly see when we look at the world — something that takes time, practice, and awareness that youth rarely affords — is central to our sense of well-being. But if happiness is a habit to be cultivated, so is its opposite: Lest we forget, 40-year-old Eliot reminds us in The Mill on the Floss that “one gets a bad habit of being unhappy.” Fortunately, Eliot did grow her own capacity for contentment with age." (Maria Popova\'s review on Tali Sharot\'s The Science of Optimism: Why We’re Hard-Wired for Hope, 2012 - Brain Pickings'

In [67]:
import random

# Create an empty list to store the random integers
random_integers = []

# Use a for loop to generate 100 random integers
for i in range(100):
    random_integers.append(random.randint(0, 1800))

In [69]:
len(random_integers)

100

In [73]:
recommendation_dict = {}
for i in random_integers:
    content_similarities = cosine_similarity(np.array(latent_df.iloc[i]).reshape(1, -1), latent_df).flatten()

    reco = pd.DataFrame(content_similarities)
    reco = reco.set_index(data.index)
    reco = reco.rename(columns={0:'similarity'})

    top_reco = reco.sort_values(by=['similarity'], ascending=False).head(5)

    recommendation_dict[top_reco.index[0]] = data.loc[top_reco.index[0]]['text'], data.loc[top_reco.index[1]]['text'], data.loc[top_reco.index[2]]['text']

In [74]:
test = pd.DataFrame.from_dict(recommendation_dict)

In [75]:
# Transpose the DataFrame
df_transposed = test.T

# Rename the columns to reflect Reference 1 and Reference 2
df_transposed.columns = ['Original text', 'Recommendation 1', 'Recommendation 2']

# Reset the index to get a clean DataFrame
df_transposed.reset_index(inplace=True)

# Rename the index column to something meaningful (optional)
df_transposed.rename(columns={'index': 'Reference Number'}, inplace=True)

df_transposed

,Reference Number,Original text,Recommendation 1,Recommendation 2
0,E1.6.G.1.5_REF1.2_PH,"""PROPOSITION 19 The human mind has no knowledg...","23 The mind does not know itself, except in so...","""PROPOSITION 13 [...] NOTE [...] I will only ..."
1,E1.6.B.1.6_REF1_PH,"LEWIS HYDE ON WORK VS. LABOR ""Work is what we ...","""""""A consumer society. It is often said that...","""47 paintings, 31 etchings & 6 self-portrait d..."
2,E1.7.B.3.6.b_REF1_PH,"""Slingerland frames the paradoxical premise at...","""""""9. It apparently makes little difference wh...","""""""We must give priority to [the] experience o..."
3,E1.6.E.2.1.b_REF1_PH,"""What makes a life meaningful? Is the choice o...","""What makes a life meaningful? Is the choice o...","""I do not like the idea of happyness — it is t..."
4,E1.6.F.2.8.a_REF2.1.a.2_LIT,"""Dear Mother, It began with the article about...","""WILD GEESE You do not have to be good. You d...","""AFTER READING LUCRETIUS, I GO TO THE POND Th..."
...,...,...,...,...
91,E1.6.C.2.12.e_REF1_PH,"""Few of us are entirely well balanced. Our psy...","""Few of us are entirely well balanced. Our psy...","SALVATION THROUGHT ART AND FORGIVENESS ""In my..."
92,E1.6.C.1.6_REF5_PO,"""LIFE STORY When I lived under the black oaks...","""LIFE STORY When I lived under the black oaks...","""I depart as air, I shake my white locks at th..."
93,E1.5.F.2_REF4.1_SCI,"""How Loneliness Reshapes the Brain Feelings of...",How Loneliness Reshapes the Brain Feelings of ...,"""There is a kind of loneliness that lodges its..."
94,E1.6.B.2.9_REF1_CUR,"""One Year Performance 1978-1979 (Cage Piece) I...","""One Year Performance 1981-1982 (Outdoor Piece...","""Several hours per week, a person standing in ..."
95,E1.6.B.2.1.a_REF7_PO,"""I slept and dreamt that life was joy. I awoke...","""I slept and dreamt that life was joy. I awoke...","""I am not desponding by nature, and after a co..."

In [81]:
df_transposed['Original text'].iloc[50], df_transposed['Recommendation 1'].iloc[50]

('BEFORE WE CAME TO BELIEVE HUMANS WERE SO IMPORTANT... ALL   EVERYTHING   HOME "SINGULARITY (after Stephen Hawking)  Do you sometimes want to wake up to the singularity we once were?  so compact nobody needed a bed, or food or money —  nobody hiding in the school bathroom or home alone  pulling open the drawer where the pills are kept.  For every atom belonging to me as good Belongs to you.   Remember?  There was no   Nature.    No  them.   No tests  to determine if the elephant grieves her calf    or if  the coral reef feels pain.    Trashed oceans don’t speak English or Farsi or French;  would that we could wake up   to what we were — when we were ocean    and before that  to when sky was earth, and animal was energy, and rock was liquid and stars were space and space was not  at all — nothing  before we came to believe humans were so important before this awful loneliness.  Can molecules recall it? what once was?    before anything happened?  No I, no We, no one. No was No verb      no noun only a tiny tiny dot brimming with  is is is is is  All   everything   home" (Marie Howe)  Watch the wonderfull animation on the poem said by the author on Vimeo: https://vimeo.com/411239105',
 '"I celebrate myself, and sing myself,  And what I assume you shall assume, For every atom belonging to me as good belongs to you.  I loafe and invite my soul, I lean and loafe at my ease observing a spear of summer grass.   My tongue, every atom of my blood, form\'d from this soil, this air, Born here of parents born here from parents the same, and their parents the same" (Walt Whitman, Leaves of grass, 1855)')

In [83]:
# df_transposed.to_csv('df_reco_test.csv',sep=',', index=True)